web:
  restart: always
  build: ./app
  expose:
    - "5000"
  links:
    - mongodb:mongodb
  volumes:
    - .:/app
  env_file: .env
  environment:
    DEBUG: 'false'
  command: /usr/local/bin/gunicorn app:app -w 2 -b :5000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "443:443"
  expose:
    - "443"
  volumes_from:
    - web
  links:
    - web:web

mongodb:
  restart: always
  image: mongo:latest
  ports:
    - "27017:27017"
  volumes:
    - /Users/weizhenyuan/mongo/data/db:/data/db



